--[[
	Wowhead-style consumables per class + spec (Midnight S1).
	Generated by tools/generate_consumables_lua.py — edit JSON and re-run.
	Item names resolve in-game via item ID.
]]

local addonName, ns = ...

ns.ConsumablesWowheadMeta = {
	gameVersion = "12.0.5",
	contentPhase = "Midnight Season 1",
	generatedAt = "2026-05-18",
	patchedSince = "2026-08-19: Season 2 health potion (Concentrated Silvermoon) only",
}

ns.ConsumablesWowheadByClassSpec = {}
ns.ConsumablesWowheadByClassSpec.DEATHKNIGHT = {
	[1] = {
		omitWeaponOil = true,
		flask = {
			best = { 241324 },
			alternates = { 241326, 241320 },
			noteKey = "CONS_NOTE_13",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241297 },
			noteKey = "CONS_NOTE_15",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 242745 },
			alternates = { 242273, 266996 },
			noteKey = "CONS_NOTE_09",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
	[2] = {
		omitWeaponOil = true,
		flask = {
			best = { 241322 },
			alternates = { 241326, 241324, 241320 },
			noteKey = "CONS_NOTE_01",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266985 },
			alternates = { 255845, 266996 },
			noteKey = "CONS_NOTE_07",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
	[3] = {
		omitWeaponOil = true,
		flask = {
			best = { 241322 },
			alternates = { 241324, 241326, 241320 },
			noteKey = "CONS_NOTE_01",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266985 },
			alternates = { 255845, 266996 },
			noteKey = "CONS_NOTE_07",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
}

ns.ConsumablesWowheadByClassSpec.DEMONHUNTER = {
	[1] = {
		flask = {
			best = { 241326 },
			alternates = { 241322, 241324, 241320 },
			noteKey = "CONS_NOTE_01",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266985 },
			alternates = { 255845, 266996 },
			noteKey = "CONS_NOTE_07",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
	[2] = {
		flask = {
			best = { 241324 },
			alternates = { 241320, 241326 },
			noteKey = "CONS_NOTE_13",
		},
		combatPotion = {
			best = { 241292 },
			alternates = { 241309, 241288 },
			noteKey = "CONS_NOTE_15",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 242745 },
			alternates = { 242273, 266996 },
			noteKey = "CONS_NOTE_09",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
	[3] = {
		flask = {
			best = { 241322 },
			alternates = { 241324, 241326, 241320 },
			noteKey = "CONS_NOTE_05",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 255845 },
			alternates = { 266985, 266996 },
			noteKey = "CONS_NOTE_06",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
}

ns.ConsumablesWowheadByClassSpec.DRUID = {
	[1] = {
		flask = {
			best = { 241322 },
			alternates = { 241324, 241326, 241320 },
			noteKey = "CONS_NOTE_05",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteKey = "CONS_NOTE_06",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
	[2] = {
		flask = {
			best = { 241326 },
			alternates = { 241322, 241324, 241320 },
			noteKey = "CONS_NOTE_01",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266985 },
			alternates = { 255845, 266996 },
			noteKey = "CONS_NOTE_07",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
	[3] = {
		flask = {
			best = { 241320 },
			alternates = { 241324, 241326 },
			noteKey = "CONS_NOTE_13",
		},
		combatPotion = {
			best = { 241292 },
			alternates = { 241309, 241288 },
			noteKey = "CONS_NOTE_15",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 242745 },
			alternates = { 242273, 266996 },
			noteKey = "CONS_NOTE_09",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
	[4] = {
		flask = {
			best = { 241324 },
			alternates = { 241322, 241326, 241320 },
			noteKey = "CONS_NOTE_03",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241288, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteKey = "CONS_NOTE_06",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
}

ns.ConsumablesWowheadByClassSpec.EVOKER = {
	[1] = {
		flask = {
			best = { 241322 },
			alternates = { 241324, 241326, 241320 },
			noteKey = "CONS_NOTE_05",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteKey = "CONS_NOTE_06",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
	[2] = {
		flask = {
			best = { 241324 },
			alternates = { 241322, 241326, 241320 },
			noteKey = "CONS_NOTE_03",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteKey = "CONS_NOTE_06",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
	[3] = {
		flask = {
			best = { 241322 },
			alternates = { 241324, 241326, 241320 },
			noteKey = "CONS_NOTE_05",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteKey = "CONS_NOTE_06",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
}

ns.ConsumablesWowheadByClassSpec.HUNTER = {
	[1] = {
		flask = {
			best = { 241326 },
			alternates = { 241322, 241324, 241320 },
			noteKey = "CONS_NOTE_01",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266985 },
			alternates = { 255845, 266996 },
			noteKey = "CONS_NOTE_07",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
	[2] = {
		flask = {
			best = { 241326 },
			alternates = { 241322, 241324, 241320 },
			noteKey = "CONS_NOTE_01",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266985 },
			alternates = { 255845, 266996 },
			noteKey = "CONS_NOTE_07",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
	[3] = {
		flask = {
			best = { 241326 },
			alternates = { 241322, 241324, 241320 },
			noteKey = "CONS_NOTE_01",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266985 },
			alternates = { 255845, 266996 },
			noteKey = "CONS_NOTE_07",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
}

ns.ConsumablesWowheadByClassSpec.MAGE = {
	[1] = {
		flask = {
			best = { 241322 },
			alternates = { 241324, 241326, 241320 },
			noteKey = "CONS_NOTE_05",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteKey = "CONS_NOTE_06",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
	[2] = {
		flask = {
			best = { 241322 },
			alternates = { 241324, 241326, 241320 },
			noteKey = "CONS_NOTE_05",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteKey = "CONS_NOTE_06",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
	[3] = {
		flask = {
			best = { 241322 },
			alternates = { 241324, 241326, 241320 },
			noteKey = "CONS_NOTE_05",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteKey = "CONS_NOTE_06",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
}

ns.ConsumablesWowheadByClassSpec.MONK = {
	[1] = {
		flask = {
			best = { 241324 },
			alternates = { 241320, 241326 },
			noteKey = "CONS_NOTE_13",
		},
		combatPotion = {
			best = { 241292 },
			alternates = { 241309, 241288 },
			noteKey = "CONS_NOTE_15",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 242745 },
			alternates = { 242273, 266996 },
			noteKey = "CONS_NOTE_09",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
	[2] = {
		flask = {
			best = { 241324 },
			alternates = { 241322, 241326, 241320 },
			noteKey = "CONS_NOTE_03",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteKey = "CONS_NOTE_06",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
	[3] = {
		flask = {
			best = { 241326 },
			alternates = { 241322, 241324, 241320 },
			noteKey = "CONS_NOTE_01",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266985 },
			alternates = { 255845, 266996 },
			noteKey = "CONS_NOTE_07",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
}

ns.ConsumablesWowheadByClassSpec.PALADIN = {
	[1] = {
		flask = {
			best = { 241324 },
			alternates = { 241322, 241326, 241320 },
			noteKey = "CONS_NOTE_03",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteKey = "CONS_NOTE_06",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
	[2] = {
		flask = {
			best = { 241324 },
			alternates = { 241320, 241326 },
			noteKey = "CONS_NOTE_13",
		},
		combatPotion = {
			best = { 241292 },
			alternates = { 241309, 241288 },
			noteKey = "CONS_NOTE_15",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 242745 },
			alternates = { 242273, 266996 },
			noteKey = "CONS_NOTE_09",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
	[3] = {
		flask = {
			best = { 241326 },
			alternates = { 241322, 241324, 241320 },
			noteKey = "CONS_NOTE_01",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266985 },
			alternates = { 255845, 266996 },
			noteKey = "CONS_NOTE_07",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
}

ns.ConsumablesWowheadByClassSpec.PRIEST = {
	[1] = {
		flask = {
			best = { 241324 },
			alternates = { 241322, 241326, 241320 },
			noteKey = "CONS_NOTE_03",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteKey = "CONS_NOTE_06",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
	[2] = {
		flask = {
			best = { 241324 },
			alternates = { 241322, 241326, 241320 },
			noteKey = "CONS_NOTE_03",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteKey = "CONS_NOTE_06",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
	[3] = {
		flask = {
			best = { 241322 },
			alternates = { 241324, 241326, 241320 },
			noteKey = "CONS_NOTE_05",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteKey = "CONS_NOTE_06",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
}

ns.ConsumablesWowheadByClassSpec.ROGUE = {
	[1] = {
		flask = {
			best = { 241322 },
			alternates = { 241326, 241324, 241320 },
			noteKey = "CONS_NOTE_01",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266985 },
			alternates = { 255845, 266996 },
			noteKey = "CONS_NOTE_07",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
	[2] = {
		flask = {
			best = { 241326 },
			alternates = { 241322, 241324, 241320 },
			noteKey = "CONS_NOTE_01",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266985 },
			alternates = { 255845, 266996 },
			noteKey = "CONS_NOTE_07",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
	[3] = {
		flask = {
			best = { 241322 },
			alternates = { 241326, 241324, 241320 },
			noteKey = "CONS_NOTE_01",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266985 },
			alternates = { 255845, 266996 },
			noteKey = "CONS_NOTE_07",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
}

ns.ConsumablesWowheadByClassSpec.SHAMAN = {
	[1] = {
		flask = {
			best = { 241322 },
			alternates = { 241324, 241326, 241320 },
			noteKey = "CONS_NOTE_05",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_10",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteKey = "CONS_NOTE_06",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
	[2] = {
		flask = {
			best = { 241326 },
			alternates = { 241322, 241324, 241320 },
			noteKey = "CONS_NOTE_01",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_11",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266985 },
			alternates = { 255845, 266996 },
			noteKey = "CONS_NOTE_07",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
	[3] = {
		flask = {
			best = { 241324 },
			alternates = { 241322, 241326, 241320 },
			noteKey = "CONS_NOTE_03",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteKey = "CONS_NOTE_06",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
}

ns.ConsumablesWowheadByClassSpec.WARLOCK = {
	[1] = {
		flask = {
			best = { 241322 },
			alternates = { 241324, 241326, 241320 },
			noteKey = "CONS_NOTE_05",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteKey = "CONS_NOTE_06",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
	[2] = {
		flask = {
			best = { 241322 },
			alternates = { 241324, 241326, 241320 },
			noteKey = "CONS_NOTE_05",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteKey = "CONS_NOTE_06",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
	[3] = {
		flask = {
			best = { 241322 },
			alternates = { 241324, 241326, 241320 },
			noteKey = "CONS_NOTE_05",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteKey = "CONS_NOTE_06",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
}

ns.ConsumablesWowheadByClassSpec.WARRIOR = {
	[1] = {
		flask = {
			best = { 241326 },
			alternates = { 241322, 241324, 241320 },
			noteKey = "CONS_NOTE_01",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266985 },
			alternates = { 255845, 266996 },
			noteKey = "CONS_NOTE_07",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
	[2] = {
		flask = {
			best = { 241324 },
			alternates = { 241326, 241322, 241320 },
			noteKey = "CONS_NOTE_01",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteKey = "CONS_NOTE_14",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 266985 },
			alternates = { 255845, 266996 },
			noteKey = "CONS_NOTE_07",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
	[3] = {
		flask = {
			best = { 241324 },
			alternates = { 241320, 241326 },
			noteKey = "CONS_NOTE_13",
		},
		combatPotion = {
			best = { 241292 },
			alternates = { 241309, 241288 },
			noteKey = "CONS_NOTE_15",
		},
		healingPotion = {
			best = { 271883, 271884 },
			alternates = { 241304, 241305 },
			noteKey = "CONS_NOTE_04",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteKey = "CONS_NOTE_12",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteKey = "CONS_NOTE_02",
		},
		feast = {
			best = { 242745 },
			alternates = { 242273, 266996 },
			noteKey = "CONS_NOTE_09",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteKey = "CONS_NOTE_08",
		},
	},
}

