--[[
	Wowhead-style consumables per class + spec (Midnight S1).
	Generated by tools/generate_consumables_lua.py — edit JSON and re-run.
	Item names resolve in-game via item ID.
]]

local addonName, ns = ...

ns.ConsumablesWowheadMeta = {
	gameVersion = "12.0.5",
	contentPhase = "Midnight Season 1",
	generatedAt = "2026-05-18",
}

ns.ConsumablesWowheadByClassSpec = {}
ns.ConsumablesWowheadByClassSpec.DEATHKNIGHT = {
	[1] = {
		omitWeaponOil = true,
		flask = {
			best = { 241324 },
			alternates = { 241326, 241320 },
			noteEn = "Use the listed flask as the default tank choice; swap to Versatility when you want a safer defensive fallback.",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241297 },
			noteEn = "Use this as the default tank potion when you want throughput with manageable risk.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 242745 },
			alternates = { 242273, 266996 },
			noteEn = "Secondary-stat feast is a strong tank choice; primary-stat feast is a safe alternative.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
	[2] = {
		omitWeaponOil = true,
		flask = {
			best = { 241322 },
			alternates = { 241326, 241324, 241320 },
			noteEn = "Critical Strike is the default throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266985 },
			alternates = { 255845, 266996 },
			noteEn = "Primary-stat feast is the safe group default.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
	[3] = {
		omitWeaponOil = true,
		flask = {
			best = { 241322 },
			alternates = { 241324, 241326, 241320 },
			noteEn = "Critical Strike is the default throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266985 },
			alternates = { 255845, 266996 },
			noteEn = "Primary-stat feast is the safe group default.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
}

ns.ConsumablesWowheadByClassSpec.DEMONHUNTER = {
	[1] = {
		flask = {
			best = { 241326 },
			alternates = { 241322, 241324, 241320 },
			noteEn = "Critical Strike is the default throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266985 },
			alternates = { 255845, 266996 },
			noteEn = "Primary-stat feast is the safe group default.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
	[2] = {
		flask = {
			best = { 241324 },
			alternates = { 241320, 241326 },
			noteEn = "Use the listed flask as the default tank choice; swap to Versatility when you want a safer defensive fallback.",
		},
		combatPotion = {
			best = { 241292 },
			alternates = { 241309, 241288 },
			noteEn = "Use this as the default tank potion when you want throughput with manageable risk.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 242745 },
			alternates = { 242273, 266996 },
			noteEn = "Secondary-stat feast is a strong tank choice; primary-stat feast is a safe alternative.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
}

ns.ConsumablesWowheadByClassSpec.DRUID = {
	[1] = {
		flask = {
			best = { 241322 },
			alternates = { 241324, 241326, 241320 },
			noteEn = "Mastery is the default throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteEn = "Primary-stat feast is the safe group default for Intellect specs.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
	[2] = {
		flask = {
			best = { 241326 },
			alternates = { 241322, 241324, 241320 },
			noteEn = "Critical Strike is the default throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266985 },
			alternates = { 255845, 266996 },
			noteEn = "Primary-stat feast is the safe group default.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
	[3] = {
		flask = {
			best = { 241320 },
			alternates = { 241324, 241326 },
			noteEn = "Use the listed flask as the default tank choice; swap to Versatility when you want a safer defensive fallback.",
		},
		combatPotion = {
			best = { 241292 },
			alternates = { 241309, 241288 },
			noteEn = "Use this as the default tank potion when you want throughput with manageable risk.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 242745 },
			alternates = { 242273, 266996 },
			noteEn = "Secondary-stat feast is a strong tank choice; primary-stat feast is a safe alternative.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
	[4] = {
		flask = {
			best = { 241324 },
			alternates = { 241322, 241326, 241320 },
			noteEn = "Haste is the default healer throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteEn = "Primary-stat feast is the safe group default for Intellect specs.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
}

ns.ConsumablesWowheadByClassSpec.EVOKER = {
	[1] = {
		flask = {
			best = { 241322 },
			alternates = { 241324, 241326, 241320 },
			noteEn = "Mastery is the default throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteEn = "Primary-stat feast is the safe group default for Intellect specs.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
	[2] = {
		flask = {
			best = { 241324 },
			alternates = { 241322, 241326, 241320 },
			noteEn = "Haste is the default healer throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteEn = "Primary-stat feast is the safe group default for Intellect specs.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
	[3] = {
		flask = {
			best = { 241322 },
			alternates = { 241324, 241326, 241320 },
			noteEn = "Mastery is the default throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteEn = "Primary-stat feast is the safe group default for Intellect specs.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
}

ns.ConsumablesWowheadByClassSpec.HUNTER = {
	[1] = {
		flask = {
			best = { 241326 },
			alternates = { 241322, 241324, 241320 },
			noteEn = "Critical Strike is the default throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266985 },
			alternates = { 255845, 266996 },
			noteEn = "Primary-stat feast is the safe group default.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
	[2] = {
		flask = {
			best = { 241326 },
			alternates = { 241322, 241324, 241320 },
			noteEn = "Critical Strike is the default throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266985 },
			alternates = { 255845, 266996 },
			noteEn = "Primary-stat feast is the safe group default.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
	[3] = {
		flask = {
			best = { 241326 },
			alternates = { 241322, 241324, 241320 },
			noteEn = "Critical Strike is the default throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266985 },
			alternates = { 255845, 266996 },
			noteEn = "Primary-stat feast is the safe group default.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
}

ns.ConsumablesWowheadByClassSpec.MAGE = {
	[1] = {
		flask = {
			best = { 241322 },
			alternates = { 241324, 241326, 241320 },
			noteEn = "Mastery is the default throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteEn = "Primary-stat feast is the safe group default for Intellect specs.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
	[2] = {
		flask = {
			best = { 241322 },
			alternates = { 241324, 241326, 241320 },
			noteEn = "Mastery is the default throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteEn = "Primary-stat feast is the safe group default for Intellect specs.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
	[3] = {
		flask = {
			best = { 241322 },
			alternates = { 241324, 241326, 241320 },
			noteEn = "Mastery is the default throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteEn = "Primary-stat feast is the safe group default for Intellect specs.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
}

ns.ConsumablesWowheadByClassSpec.MONK = {
	[1] = {
		flask = {
			best = { 241324 },
			alternates = { 241320, 241326 },
			noteEn = "Use the listed flask as the default tank choice; swap to Versatility when you want a safer defensive fallback.",
		},
		combatPotion = {
			best = { 241292 },
			alternates = { 241309, 241288 },
			noteEn = "Use this as the default tank potion when you want throughput with manageable risk.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 242745 },
			alternates = { 242273, 266996 },
			noteEn = "Secondary-stat feast is a strong tank choice; primary-stat feast is a safe alternative.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
	[2] = {
		flask = {
			best = { 241324 },
			alternates = { 241322, 241326, 241320 },
			noteEn = "Haste is the default healer throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteEn = "Primary-stat feast is the safe group default for Intellect specs.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
	[3] = {
		flask = {
			best = { 241326 },
			alternates = { 241322, 241324, 241320 },
			noteEn = "Critical Strike is the default throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266985 },
			alternates = { 255845, 266996 },
			noteEn = "Primary-stat feast is the safe group default.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
}

ns.ConsumablesWowheadByClassSpec.PALADIN = {
	[1] = {
		flask = {
			best = { 241324 },
			alternates = { 241322, 241326, 241320 },
			noteEn = "Haste is the default healer throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteEn = "Primary-stat feast is the safe group default for Intellect specs.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
	[2] = {
		flask = {
			best = { 241324 },
			alternates = { 241320, 241326 },
			noteEn = "Use the listed flask as the default tank choice; swap to Versatility when you want a safer defensive fallback.",
		},
		combatPotion = {
			best = { 241292 },
			alternates = { 241309, 241288 },
			noteEn = "Use this as the default tank potion when you want throughput with manageable risk.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 242745 },
			alternates = { 242273, 266996 },
			noteEn = "Secondary-stat feast is a strong tank choice; primary-stat feast is a safe alternative.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
	[3] = {
		flask = {
			best = { 241326 },
			alternates = { 241322, 241324, 241320 },
			noteEn = "Critical Strike is the default throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266985 },
			alternates = { 255845, 266996 },
			noteEn = "Primary-stat feast is the safe group default.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
}

ns.ConsumablesWowheadByClassSpec.PRIEST = {
	[1] = {
		flask = {
			best = { 241324 },
			alternates = { 241322, 241326, 241320 },
			noteEn = "Haste is the default healer throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteEn = "Primary-stat feast is the safe group default for Intellect specs.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
	[2] = {
		flask = {
			best = { 241324 },
			alternates = { 241322, 241326, 241320 },
			noteEn = "Haste is the default healer throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteEn = "Primary-stat feast is the safe group default for Intellect specs.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
	[3] = {
		flask = {
			best = { 241322 },
			alternates = { 241324, 241326, 241320 },
			noteEn = "Mastery is the default throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteEn = "Primary-stat feast is the safe group default for Intellect specs.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
}

ns.ConsumablesWowheadByClassSpec.ROGUE = {
	[1] = {
		flask = {
			best = { 241322 },
			alternates = { 241326, 241324, 241320 },
			noteEn = "Critical Strike is the default throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266985 },
			alternates = { 255845, 266996 },
			noteEn = "Primary-stat feast is the safe group default.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
	[2] = {
		flask = {
			best = { 241326 },
			alternates = { 241322, 241324, 241320 },
			noteEn = "Critical Strike is the default throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266985 },
			alternates = { 255845, 266996 },
			noteEn = "Primary-stat feast is the safe group default.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
	[3] = {
		flask = {
			best = { 241322 },
			alternates = { 241326, 241324, 241320 },
			noteEn = "Critical Strike is the default throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266985 },
			alternates = { 255845, 266996 },
			noteEn = "Primary-stat feast is the safe group default.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
}

ns.ConsumablesWowheadByClassSpec.SHAMAN = {
	[1] = {
		flask = {
			best = { 241322 },
			alternates = { 241324, 241326, 241320 },
			noteEn = "Mastery is the default throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use Thalassian Phoenix Oil unless Flametongue Weapon is preferred by your current build.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteEn = "Primary-stat feast is the safe group default for Intellect specs.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
	[2] = {
		flask = {
			best = { 241326 },
			alternates = { 241322, 241324, 241320 },
			noteEn = "Critical Strike is the default throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use Thalassian Phoenix Oil unless Windfury/Flametongue weapon imbues are required by your build.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266985 },
			alternates = { 255845, 266996 },
			noteEn = "Primary-stat feast is the safe group default.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
	[3] = {
		flask = {
			best = { 241324 },
			alternates = { 241322, 241326, 241320 },
			noteEn = "Haste is the default healer throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteEn = "Primary-stat feast is the safe group default for Intellect specs.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
}

ns.ConsumablesWowheadByClassSpec.WARLOCK = {
	[1] = {
		flask = {
			best = { 241322 },
			alternates = { 241324, 241326, 241320 },
			noteEn = "Mastery is the default throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteEn = "Primary-stat feast is the safe group default for Intellect specs.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
	[2] = {
		flask = {
			best = { 241322 },
			alternates = { 241324, 241326, 241320 },
			noteEn = "Mastery is the default throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteEn = "Primary-stat feast is the safe group default for Intellect specs.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
	[3] = {
		flask = {
			best = { 241322 },
			alternates = { 241324, 241326, 241320 },
			noteEn = "Mastery is the default throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241309 },
			alternates = { 241288, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266996 },
			alternates = { 255846, 266985 },
			noteEn = "Primary-stat feast is the safe group default for Intellect specs.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
}

ns.ConsumablesWowheadByClassSpec.WARRIOR = {
	[1] = {
		flask = {
			best = { 241326 },
			alternates = { 241322, 241324, 241320 },
			noteEn = "Critical Strike is the default throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266985 },
			alternates = { 255845, 266996 },
			noteEn = "Primary-stat feast is the safe group default.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
	[2] = {
		flask = {
			best = { 241324 },
			alternates = { 241326, 241322, 241320 },
			noteEn = "Critical Strike is the default throughput flask; sim your character for close secondary stats.",
		},
		combatPotion = {
			best = { 241288 },
			alternates = { 241309, 241292 },
			noteEn = "Use the listed potion as the default burst/throughput choice for PvE.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 266985 },
			alternates = { 255845, 266996 },
			noteEn = "Primary-stat feast is the safe group default.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
	[3] = {
		flask = {
			best = { 241324 },
			alternates = { 241320, 241326 },
			noteEn = "Use the listed flask as the default tank choice; swap to Versatility when you want a safer defensive fallback.",
		},
		combatPotion = {
			best = { 241292 },
			alternates = { 241309, 241288 },
			noteEn = "Use this as the default tank potion when you want throughput with manageable risk.",
		},
		healingPotion = {
			best = { 241304 },
			alternates = {  },
			noteEn = "Highest verified Midnight health potion.",
		},
		weaponOil = {
			best = { 243734 },
			alternates = {  },
			noteEn = "Use as the default temporary weapon buff unless your class/spec-specific weapon imbue overrides it.",
		},
		augmentRune = {
			best = { 259085 },
			alternates = {  },
			noteEn = "Current Midnight Season 1 augment rune.",
		},
		feast = {
			best = { 242745 },
			alternates = { 242273, 266996 },
			noteEn = "Secondary-stat feast is a strong tank choice; primary-stat feast is a safe alternative.",
		},
		personalFood = {
			best = { 242747 },
			alternates = { 242275, 268679, 255847 },
			noteEn = "Primary-stat personal food is the safe default when no feast is available.",
		},
	},
}

