-- AUTO-GENERATED by tools/build_flight_network.py — do not edit by hand.
--
-- Which flight points can actually reach each other. Generated from
-- ZygorGuidesViewer/Libs-Retail/LibTaxi-1.0/data.lua by walking its taxi graph and
-- numbering the CONNECTED COMPONENTS: two names with the same number have a path
-- between them, two with different numbers provably do not.
--
-- 🔴 WHY THIS EXISTS. Rob, 3 Sep 2026, in Harandar: "Fly from The Den to Torntusk
-- Overlook." Harandar's taxi network is a closed five-node star with no outbound
-- edge; Torntusk Overlook is on the Eastern Kingdoms network. FlightPointsData holds
-- no edges at all, so it could not know, and any "nearest here + nearest there"
-- pairing kept producing flights nobody can take.
--
-- ⚠️ A name that is ABSENT here means unknown, not unconnected. Callers must treat
-- nil as "say nothing", never as "no path" — Zygor's graph does not cover every
-- point we ship, and silence is the honest answer for a point neither source knows.
local _, ns = ...

ns.FLIGHT_NETWORK = {
	["Amani Foothold"] = 1,
	["Amani'Zar Village"] = 1,
	["Antecedent Isle"] = 22,
	["Apex Observatory"] = 25,
	["Arcae Locus"] = 24,
	["Aspirant's Rest"] = 18,
	["Atal'Aman"] = 1,
	["Atal'Gral"] = 13,
	["Azure Archives"] = 25,
	["Bel'ameth"] = 25,
	["Camber Alcove"] = 24,
	["Camp Antonidas"] = 25,
	["Camp Murroch"] = 27,
	["Camp Nowhere"] = 25,
	["Camp Stonewash"] = 1,
	["Central Encampment"] = 28,
	["Cragthorn Highlands"] = 29,
	["Demolition Dome"] = 30,
	["Dormant Alcove"] = 24,
	["Dornogal"] = 27,
	["Dragonscale Basecamp"] = 25,
	["Dragonscale Camp"] = 25,
	["Dunelle's Kindness"] = 27,
	["Durgaz Cabin"] = 27,
	["Elysian Hold"] = 18,
	["Entrance Gate"] = 29,
	["Extraction Coast"] = 37,
	["Eye of Ysera"] = 28,
	["Faerin's Advance"] = 27,
	["Fairbreeze Village"] = 1,
	["Faith's Repose"] = 20,
	["Freywold Village"] = 27,
	["Fulgor Alcove"] = 24,
	["Garden Shrine"] = 25,
	["Gelikyr Post"] = 25,
	["Gravid Repose Locus"] = 21,
	["Gundargaz"] = 27,
	["Gutterville"] = 27,
	["Har'alnor"] = 35,
	["Har'athir"] = 35,
	["Har'kuai"] = 35,
	["Har'mara"] = 35,
	["Haven"] = 20,
	["Hellfire Peninsula, The Dark Portal"] = 3,
	["Hero's Rest"] = 18,
	["Hillhelm Family Farm"] = 27,
	["Howling Ridge"] = 33,
	["Interior Locus"] = 21,
	["Iskaara"] = 25,
	["Keeper's Respite"] = 19,
	["Life Vault Ruins"] = 25,
	["Light's Redoubt"] = 27,
	["Lightspark"] = 27,
	["Loamm"] = 25,
	["Locus Point"] = 33,
	["Lorel's Crossing"] = 27,
	["Mereldar"] = 27,
	["Mmarl"] = 27,
	["Moonglade"] = 2,
	["Morqut Village"] = 25,
	["Nexus Port"] = 37,
	["Obsidian Bulwark"] = 25,
	["Obsidian Rest"] = 25,
	["Obsidian Throne"] = 25,
	["Opportunity Point"] = 27,
	["Oribos"] = 16,
	["Pilgrim's Grace"] = 20,
	["Primus Locus"] = 21,
	["Priory of the Sacred Flame"] = 27,
	["Quartus Locus"] = 21,
	["Quintus Locus"] = 21,
	["Rambleshire"] = 27,
	["Repertory Alcove"] = 24,
	["Rhonin's Shield"] = 25,
	["Rondure Alcove"] = 24,
	["Ruby Life Pools"] = 25,
	["Runetotem's Bounty North"] = 29,
	["Runetotem's Bounty South"] = 29,
	["Saltfang Shoals East"] = 29,
	["Sanctum of Light"] = 1,
	["Secundus Locus"] = 21,
	["Sepulcher Overlook"] = 23,
	["Sepulcher of the First Ones"] = 23,
	["Shadebasin Watch"] = 1,
	["Shadowvein Point"] = 27,
	["Shattered Landing"] = 1,
	["Shifting Sands"] = 25,
	["Silverglade Refuge"] = 1,
	["Silvermoon City"] = 1,
	["Slam Central Station"] = 30,
	["Sporeforge"] = 37,
	["Temple of Karabor"] = 7,
	["Temporal Conflux"] = 25,
	["Terrace of the Collectors"] = 16,
	["Terrace of the Sun"] = 1,
	["Tertius Locus"] = 21,
	["The Aegis Wall"] = 27,
	["The Bloom"] = 29,
	["The Bluffs"] = 29,
	["The Common"] = 29,
	["The Den"] = 35,
	["The Exodar"] = 2,
	["The Gallagio"] = 30,
	["The Heaps"] = 30,
	["The Incontinental Hotel"] = 30,
	["The Ingress"] = 33,
	["The Royal Exchange"] = 1,
	["Theron's Watch"] = 25,
	["Three-Falls Lookout"] = 25,
	["Tokka's Landing"] = 1,
	["Torntusk Overlook"] = 1,
	["Tranquil Strand"] = 27,
	["Tranquillien"] = 1,
	["Uktulut Backwater"] = 25,
	["Uktulut Outpost"] = 25,
	["Uktulut Pier"] = 25,
	["Ultimus Locus"] = 21,
	["Valdrakken"] = 25,
	["Vault of the Incarnates"] = 25,
	["Ve'nari's Refuge"] = 19,
	["Veiled Ossuary"] = 25,
	["Verdant Landing"] = 28,
	["Weaver's Lair"] = 27,
	["Wellspring Overlook"] = 28,
	["Wildcamp Or'lay"] = 27,
	["Wildcamp Ul'ar"] = 27,
	["Wingrest Embassy"] = 25,
	["Witherbark Bluffs"] = 1,
	["Zovaal's Grasp"] = 22,
}

--- Can you fly from `fromName` to `toName`?
--- @return boolean|nil  true = a path exists, false = provably none, nil = we do not know
function ns.FlightPathExists(fromName, toName)
	if type(fromName) ~= "string" or type(toName) ~= "string" then
		return nil
	end
	local a, b = ns.FLIGHT_NETWORK[fromName], ns.FLIGHT_NETWORK[toName]
	if not a or not b then
		return nil -- one of them is outside Zygor's graph: unknown, not unconnected
	end
	return a == b
end
