--[[
	Team utility macros (cursor / mouseover / focus) per class + spec index.
	Generated by tools/generate_team_macros_lua.py — edit JSON and re-run to refresh.
]]

local addonName, ns = ...

ns.TeamMacrosByClassSpec = {
	DEATHKNIGHT = {
		[1] = {
			{
			id = "cursor_dnd",
			name = "Cursor DnD",
			descNl = "Plaatst Death and Decay direct op je muispositie.",
			descEn = "Cast Death and Decay at your cursor.",
			macro = [=[#showtooltip Death and Decay
/cast [@cursor] Death and Decay]=],
			},
			{
			id = "mouseover_grip",
			name = "Mouseover Grip",
			descNl = "Trekt de vijand naar je toe waar je met je muis over zweeft.",
			descEn = "Pull the enemy under your cursor to you.",
			macro = [=[#showtooltip Death Grip
/cast [@mouseover,harm,nodead][] Death Grip]=],
			},
		},
		[2] = {
			{
			id = "cursor_dnd",
			name = "Cursor DnD",
			descNl = "Plaatst Death and Decay direct op je muispositie.",
			descEn = "Cast Death and Decay at your cursor.",
			macro = [=[#showtooltip Death and Decay
/cast [@cursor] Death and Decay]=],
			},
		},
		[3] = {
			{
			id = "cursor_dnd",
			name = "Cursor DnD",
			descNl = "Plaatst Death and Decay direct op je muispositie.",
			descEn = "Cast Death and Decay at your cursor.",
			macro = [=[#showtooltip Death and Decay
/cast [@cursor] Death and Decay]=],
			},
			{
			id = "pet_hook",
			name = "Pet Hook",
			descNl = "Laat je pet direct zijn Abomination Hook gebruiken op je focus doel.",
			descEn = "Commands your pet to use Abomination Hook on your focus target.",
			macro = [=[#showtooltip Hook
/cast [@focus,harm,nodead][] Hook]=],
			},
		},
	},
	DEMONHUNTER = {
		[1] = {
			{
			id = "cursor_sigil",
			name = "Cursor Sigil",
			descNl = "Plaatst Sigil of Flame direct op je muispositie.",
			descEn = "Place Sigil of Flame at your cursor.",
			macro = [=[#showtooltip Sigil of Flame
/cast [@cursor] Sigil of Flame]=],
			},
			{
			id = "cursor_metamorphosis",
			name = "Cursor Metamorphosis",
			descNl = "Springt direct naar je muispositie voor Metamorphosis.",
			descEn = "Leap to your cursor for Metamorphosis.",
			macro = [=[#showtooltip Metamorphosis
/cast [@cursor] Metamorphosis]=],
			},
		},
		[2] = {
			{
			id = "cursor_sigils",
			name = "Cursor Sigils",
			descNl = "Plaatst al je Sigils direct op je muispositie zonder richtcirkel.",
			descEn = "Place sigils at your cursor without the targeting circle.",
			macro = [=[#showtooltip Sigil of Flame
/cast [@cursor] Sigil of Flame]=],
			},
			{
			id = "mouseover_taunt",
			name = "Mouseover Taunt",
			descNl = "Spookt vijanden aan via je muiscursor.",
			descEn = "Taunt enemies via your cursor.",
			macro = [=[#showtooltip Torment
/cast [@mouseover,harm,nodead][] Torment]=],
			},
		},
	},
	DRUID = {
		[1] = {
			{
			id = "cursor_starfall",
			name = "Cursor Starfall",
			descNl = "Plaatst Starfall direct op je muispositie.",
			descEn = "Cast Starfall at your cursor.",
			macro = [=[#showtooltip Starfall
/cast [@cursor] Starfall]=],
			},
			{
			id = "mouseover_decurse",
			name = "Mouseover Decurse",
			descNl = "Verwijdert vloeken van groepsleden via je muis.",
			descEn = "Remove curses from party members via your cursor.",
			macro = [=[#showtooltip Remove Corruption
/cast [@mouseover,help,nodead][] Remove Corruption]=],
			},
		},
		[2] = {
			{
			id = "mouseover_regrowth",
			name = "Mouseover Regrowth",
			descNl = "Heal een teamlid met je Predatory Swiftness proc zonder je target te verliezen.",
			descEn = "Heal a teammate with Predatory Swiftness without swapping your target.",
			macro = [=[#showtooltip Regrowth
/cast [@mouseover,help,nodead][] Regrowth]=],
			},
		},
		[3] = {
			{
			id = "cursor_vortex",
			name = "Cursor Vortex",
			descNl = "Plaatst Ursol's Vortex direct onder je muis.",
			descEn = "Cast Ursol's Vortex under your cursor.",
			macro = [=[#showtooltip Ursol's Vortex
/cast [@cursor] Ursol's Vortex]=],
			},
		},
		[4] = {
			{
			id = "mouseover_heals",
			name = "Mouseover Heals",
			descNl = "Cast Rejuvenation op het doel onder je muis.",
			descEn = "Cast Rejuvenation on the target under your cursor.",
			macro = [=[#showtooltip Rejuvenation
/cast [@mouseover,help,nodead][] Rejuvenation]=],
			},
			{
			id = "cursor_efflorescence",
			name = "Cursor Efflorescence",
			descNl = "Plaatst de healing cirkel direct op je muispositie.",
			descEn = "Cast the healing circle at your cursor.",
			macro = [=[#showtooltip Efflorescence
/cast [@cursor] Efflorescence]=],
			},
		},
	},
	EVOKER = {
		[1] = {
			{
			id = "hover_cancel",
			name = "Hover Cancel",
			descNl = "Zet Hover aan, of stopt het direct bij een tweede klik om snel te landen.",
			descEn = "Toggle Hover on, or cancel it on a second press to land quickly.",
			macro = [=[#showtooltip Hover
/cast Hover
/cancelaura Hover]=],
			},
			{
			id = "cursor_deep_breath",
			name = "Cursor Deep Breath",
			descNl = "Vliegt direct in een rechte lijn naar je muispositie.",
			descEn = "Fly in a straight line to your cursor.",
			macro = [=[#showtooltip Deep Breath
/cast [@cursor] Deep Breath]=],
			},
		},
		[2] = {
			{
			id = "mouseover_spiritbloom",
			name = "Mouseover Spiritbloom",
			descNl = "Healt de groep onder je muiscursor.",
			descEn = "Heal the group under your cursor.",
			macro = [=[#showtooltip Spiritbloom
/cast [@mouseover,help,nodead][] Spiritbloom]=],
			},
			{
			id = "cursor_emerald_blossom",
			name = "Cursor Emerald Blossom",
			descNl = "Plaatst de bloem direct op je muispositie.",
			descEn = "Cast Emerald Blossom at your cursor.",
			macro = [=[#showtooltip Emerald Blossom
/cast [@cursor] Emerald Blossom]=],
			},
		},
		[3] = {
			{
			id = "mouseover_rescue",
			name = "Mouseover Rescue",
			descNl = "Vliegt direct naar het teamlid onder je muis om ze te verplaatsen.",
			descEn = "Fly to the teammate under your cursor to reposition them.",
			macro = [=[#showtooltip Rescue
/cast [@mouseover,help,nodead][] Rescue]=],
			},
			{
			id = "cursor_eruption",
			name = "Cursor Eruption",
			descNl = "Cast Eruption direct op de vijand onder je muis.",
			descEn = "Cast Eruption on the enemy under your cursor.",
			macro = [=[#showtooltip Eruption
/cast [@cursor] Eruption]=],
			},
		},
	},
	HUNTER = {
		[1] = {
			{
			id = "smart_misdirection",
			name = "Smart Misdirection",
			descNl = "Misdirection op je focus (tank) indien aanwezig, anders op je pet.",
			descEn = "Misdirection on focus (tank) if set, otherwise on your pet.",
			macro = [=[#showtooltip Misdirection
/cast [@focus,help,nodead][@pet,exists,nodead][] Misdirection]=],
			},
			{
			id = "turtle_cancel",
			name = "Turtle Cancel",
			descNl = "Zet je schild aan en direct uit bij een tweede klik om weer te kunnen aanvalen.",
			descEn = "Toggle your defensive on and off so you can attack again.",
			macro = [=[#showtooltip Aspect of the Turtle
/cast Aspect of the Turtle
/cancelaura Aspect of the Turtle]=],
			},
		},
		[2] = {
			{
			id = "cursor_volley",
			name = "Cursor Volley",
			descNl = "Gooit Volley direct op je muispositie.",
			descEn = "Cast Volley at your cursor.",
			macro = [=[#showtooltip Volley
/cast [@cursor] Volley]=],
			},
			{
			id = "smart_misdirection",
			name = "Smart Misdirection",
			descNl = "Misdirection op je focus (tank) indien aanwezig, anders op je pet.",
			descEn = "Misdirection on focus (tank) if set, otherwise on your pet.",
			macro = [=[#showtooltip Misdirection
/cast [@focus,help,nodead][@pet,exists,nodead][] Misdirection]=],
			},
		},
		[3] = {
			{
			id = "cursor_traps",
			name = "Cursor Traps",
			descNl = "Gooit je vallen direct op je muiscursor.",
			descEn = "Place traps at your cursor.",
			macro = [=[#showtooltip Freezing Trap
/cast [@cursor] Freezing Trap]=],
			},
			{
			id = "mouseover_harpoon",
			name = "Mouseover Harpoon",
			descNl = "Schiethaken naar de vijand onder je muis.",
			descEn = "Harpoon the enemy under your cursor.",
			macro = [=[#showtooltip Harpoon
/cast [@mouseover,harm,nodead][] Harpoon]=],
			},
		},
	},
	MAGE = {
		[1] = {
			{
			id = "ice_block_cancel",
			name = "Ice Block Cancel",
			descNl = "Activeert Ice Block en heft het direct op bij de volgende klik.",
			descEn = "Activates Ice Block and cancels it on the next press.",
			macro = [=[#showtooltip Ice Block
/stopcasting
/cast Ice Block
/cancelaura Ice Block]=],
			},
			{
			id = "focus_polymorph",
			name = "Focus Polymorph",
			descNl = "Verandert je focus doelwit in een schaap.",
			descEn = "Polymorph your focus target into a sheep.",
			macro = [=[#showtooltip Polymorph
/cast [@focus,harm,nodead][] Polymorph]=],
			},
		},
		[2] = {
			{
			id = "cursor_flamestrike",
			name = "Cursor Flamestrike",
			descNl = "Gooit een vuurzee direct op je muispositie.",
			descEn = "Cast Flamestrike at your cursor.",
			macro = [=[#showtooltip Flamestrike
/cast [@cursor] Flamestrike]=],
			},
			{
			id = "ice_block_cancel",
			name = "Ice Block Cancel",
			descNl = "Activeert Ice Block en heft het direct op bij de volgende klik.",
			descEn = "Activates Ice Block and cancels it on the next press.",
			macro = [=[#showtooltip Ice Block
/stopcasting
/cast Ice Block
/cancelaura Ice Block]=],
			},
		},
		[3] = {
			{
			id = "cursor_blizzard",
			name = "Cursor Blizzard",
			descNl = "Plaatst Blizzard direct op je muiscursor.",
			descEn = "Cast Blizzard at your cursor.",
			macro = [=[#showtooltip Blizzard
/cast [@cursor] Blizzard]=],
			},
			{
			id = "ice_block_cancel",
			name = "Ice Block Cancel",
			descNl = "Activeert Ice Block en heft het direct op bij de volgende klik.",
			descEn = "Activates Ice Block and cancels it on the next press.",
			macro = [=[#showtooltip Ice Block
/stopcasting
/cast Ice Block
/cancelaura Ice Block]=],
			},
		},
	},
	MONK = {
		[1] = {
			{
			id = "cursor_dave",
			name = "Cursor Dave",
			descNl = "Plaatst de Ox Statue direct op je muispositie.",
			descEn = "Summon the Black Ox Statue at your cursor.",
			macro = [=[#showtooltip Summon Black Ox Statue
/cast [@cursor] Summon Black Ox Statue]=],
			},
			{
			id = "mouseover_taunt",
			name = "Mouseover Taunt",
			descNl = "Spookt vijanden aan via je muiscursor of frames.",
			descEn = "Taunt enemies via your cursor or unit frames.",
			macro = [=[#showtooltip Provoke
/cast [@mouseover,harm,nodead][] Provoke]=],
			},
		},
		[2] = {
			{
			id = "help_harm_buttons",
			name = "Help/Harm Buttons",
			descNl = "Vivify op vrienden, Tiger Palm op vijanden.",
			descEn = "Vivify on friends, Tiger Palm on enemies.",
			macro = [=[#showtooltip
/cast [@mouseover,help,nodead][help,nodead] Vivify; [@mouseover,harm,nodead][harm,nodead][] Tiger Palm]=],
			},
			{
			id = "mouseover_jade_statue",
			name = "Mouseover Jade Statue",
			descNl = "Plaatst je healing standbeeld direct op je muispositie.",
			descEn = "Summon your healing statue at your cursor.",
			macro = [=[#showtooltip Summon Jade Serpent Statue
/cast [@cursor] Summon Jade Serpent Statue]=],
			},
		},
		[3] = {
			{
			id = "cursor_ring_of_peace",
			name = "Cursor Ring of Peace",
			descNl = "Plaatst de Ring of Peace direct op je muiscursor.",
			descEn = "Cast Ring of Peace at your cursor.",
			macro = [=[#showtooltip Ring of Peace
/cast [@cursor] Ring of Peace]=],
			},
		},
	},
	PALADIN = {
		[1] = {
			{
			id = "mouseover_beacon",
			name = "Mouseover Beacon",
			descNl = "Zet Beacon of Light direct op het teamlid onder je muis.",
			descEn = "Cast Beacon of Light on the teammate under your cursor.",
			macro = [=[#showtooltip Beacon of Light
/cast [@mouseover,help,nodead][] Beacon of Light]=],
			},
			{
			id = "bubble_cancel",
			name = "Bubble Cancel",
			descNl = "Zet Divine Shield direct aan en uit om mechanics te skippen.",
			descEn = "Toggle Divine Shield on and off to skip mechanics.",
			macro = [=[#showtooltip Divine Shield
/cast Divine Shield
/cancelaura Divine Shield]=],
			},
		},
		[2] = {
			{
			id = "mouseover_blessings",
			name = "Mouseover Blessings",
			descNl = "Cast Blessing of Protection snel via je muis.",
			descEn = "Cast Blessing of Protection quickly via your mouse.",
			macro = [=[#showtooltip Blessing of Protection
/cast [@mouseover,help,nodead][] Blessing of Protection]=],
			},
			{
			id = "mouseover_taunt",
			name = "Mouseover Taunt",
			descNl = "Taunt vijanden via je muiscursor.",
			descEn = "Taunt enemies via your cursor.",
			macro = [=[#showtooltip Hand of Reckoning
/cast [@mouseover,harm,nodead][] Hand of Reckoning]=],
			},
		},
		[3] = {
			{
			id = "cursor_execution",
			name = "Cursor Execution",
			descNl = "Plaatst Execution Sentence of Final Reckoning direct op je muis.",
			descEn = "Cast Execution Sentence or Final Reckoning at your cursor.",
			macro = [=[#showtooltip Final Reckoning
/cast [@cursor] Final Reckoning]=],
			},
			{
			id = "bubble_cancel",
			name = "Bubble Cancel",
			descNl = "Zet Divine Shield direct aan en uit om door te kunnen dps'en.",
			descEn = "Toggle Divine Shield on and off so you can keep DPSing.",
			macro = [=[#showtooltip Divine Shield
/cast Divine Shield
/cancelaura Divine Shield]=],
			},
		},
	},
	PRIEST = {
		[1] = {
			{
			id = "mouseover_shield",
			name = "Mouseover Shield",
			descNl = "Plaatst Power Word: Shield direct via je muis.",
			descEn = "Cast Power Word: Shield via your cursor.",
			macro = [=[#showtooltip Power Word: Shield
/cast [@mouseover,help,nodead][] Power Word: Shield]=],
			},
			{
			id = "cursor_barrier",
			name = "Cursor Barrier",
			descNl = "Plaatst de healing koepel direct op je muispositie.",
			descEn = "Cast the healing dome at your cursor.",
			macro = [=[#showtooltip Power Word: Barrier
/cast [@cursor] Power Word: Barrier]=],
			},
		},
		[2] = {
			{
			id = "mouseover_life",
			name = "Mouseover Life",
			descNl = "Cast Leap of Faith om het teamlid onder je muis te redden.",
			descEn = "Cast Leap of Faith to pull the teammate under your cursor to safety.",
			macro = [=[#showtooltip Leap of Faith
/cast [@mouseover,help,nodead][] Leap of Faith]=],
			},
			{
			id = "cursor_sanctify",
			name = "Cursor Sanctify",
			descNl = "Gooit Holy Word: Sanctify direct op je muispositie.",
			descEn = "Cast Holy Word: Sanctify at your cursor.",
			macro = [=[#showtooltip Holy Word: Sanctify
/cast [@cursor] Holy Word: Sanctify]=],
			},
		},
		[3] = {
			{
			id = "cursor_shadow_crash",
			name = "Cursor Shadow Crash",
			descNl = "Sleutelmacro: Gooit Shadow Crash direct op je muis om snel Dots te verspreiden.",
			descEn = "Key macro: cast Shadow Crash at your cursor to spread DoTs quickly.",
			macro = [=[#showtooltip Shadow Crash
/cast [@cursor] Shadow Crash]=],
			},
		},
	},
	ROGUE = {
		[1] = {
			{
			id = "mouseover_tricks",
			name = "Mouseover Tricks",
			descNl = "Geeft direct je dreiging (threat) aan de tank onder je muis.",
			descEn = "Hands threat to the tank under your cursor.",
			macro = [=[#showtooltip Tricks of the Trade
/cast [@mouseover,help,nodead][] Tricks of the Trade]=],
			},
			{
			id = "focus_blind",
			name = "Focus Blind",
			descNl = "Gooit Blind op je focus doelwit zonder je huidige target kwijt te raken.",
			descEn = "Cast Blind on your focus without losing your current target.",
			macro = [=[#showtooltip Blind
/cast [@focus,harm,nodead][] Blind]=],
			},
		},
		[2] = {
			{
			id = "mouseover_tricks",
			name = "Mouseover Tricks",
			descNl = "Geeft direct je dreiging aan de tank onder je muis.",
			descEn = "Hands threat to the tank under your cursor.",
			macro = [=[#showtooltip Tricks of the Trade
/cast [@mouseover,help,nodead][] Tricks of the Trade]=],
			},
			{
			id = "cursor_grappling_hook",
			name = "Cursor Grappling Hook",
			descNl = "Slingert je direct naar je muispositie.",
			descEn = "Grapple to your cursor.",
			macro = [=[#showtooltip Grappling Hook
/cast [@cursor] Grappling Hook]=],
			},
		},
		[3] = {
			{
			id = "mouseover_tricks",
			name = "Mouseover Tricks",
			descNl = "Geeft direct je dreiging aan de tank onder je muis.",
			descEn = "Hands threat to the tank under your cursor.",
			macro = [=[#showtooltip Tricks of the Trade
/cast [@mouseover,help,nodead][] Tricks of the Trade]=],
			},
		},
	},
	SHAMAN = {
		[1] = {
			{
			id = "cursor_earthquake",
			name = "Cursor Earthquake",
			descNl = "Plaatst Earthquake direct onder je muis.",
			descEn = "Cast Earthquake under your cursor.",
			macro = [=[#showtooltip Earthquake
/cast [@cursor] Earthquake]=],
			},
			{
			id = "cursor_totems",
			name = "Cursor Totems",
			descNl = "Plaatst Capacitor Totem direct op je muispositie.",
			descEn = "Place Capacitor Totem at your cursor.",
			macro = [=[#showtooltip Capacitor Totem
/cast [@cursor] Capacitor Totem]=],
			},
		},
		[2] = {
			{
			id = "cursor_totems",
			name = "Cursor Totems",
			descNl = "Plaatst Windfury of Capacitor Totem direct op je muispositie.",
			descEn = "Place Windfury or Capacitor Totem at your cursor.",
			macro = [=[#showtooltip Windfury Totem
/cast [@cursor] Windfury Totem]=],
			},
		},
		[3] = {
			{
			id = "cursor_healing_rain",
			name = "Cursor Healing Rain",
			descNl = "Plaatst Healing Rain direct op je muis.",
			descEn = "Cast Healing Rain at your cursor.",
			macro = [=[#showtooltip Healing Rain
/cast [@cursor] Healing Rain]=],
			},
			{
			id = "help_harm_2_in_1",
			name = "Help/Harm 2-in-1",
			descNl = "Riptide op vrienden, Flame Shock op vijanden.",
			descEn = "Riptide on friends, Flame Shock on enemies.",
			macro = [=[#showtooltip
/cast [@mouseover,help,nodead][help,nodead] Riptide; [@mouseover,harm,nodead][harm,nodead][] Flame Shock]=],
			},
		},
	},
	WARLOCK = {
		[1] = {
			{
			id = "cursor_vile_taint",
			name = "Cursor Vile Taint",
			descNl = "Plaatst Vile Taint direct op je muispositie.",
			descEn = "Cast Vile Taint at your cursor.",
			macro = [=[#showtooltip Vile Taint
/cast [@cursor] Vile Taint]=],
			},
			{
			id = "focus_fear",
			name = "Focus Fear",
			descNl = "Cast Fear op je focus doelwit.",
			descEn = "Cast Fear on your focus target.",
			macro = [=[#showtooltip Fear
/cast [@focus,harm,nodead][] Fear]=],
			},
		},
		[2] = {
			{
			id = "cursor_guillotine",
			name = "Cursor Guillotine",
			descNl = "Gooit de bijl van je pet direct op je muispositie.",
			descEn = "Throws your pet's axe at your cursor.",
			macro = [=[#showtooltip Guillotine
/cast [@cursor] Guillotine]=],
			},
		},
		[3] = {
			{
			id = "cursor_rain_of_fire",
			name = "Cursor Rain of Fire",
			descNl = "Gooit Rain of Fire direct op je muiscursor.",
			descEn = "Cast Rain of Fire at your cursor.",
			macro = [=[#showtooltip Rain of Fire
/cast [@cursor] Rain of Fire]=],
			},
			{
			id = "mouseover_havoc",
			name = "Mouseover Havoc",
			descNl = "Plaatst Havoc op de vijand waar je met je muis over zweeft.",
			descEn = "Cast Havoc on the enemy under your cursor.",
			macro = [=[#showtooltip Havoc
/cast [@mouseover,harm,nodead][] Havoc]=],
			},
		},
	},
	WARRIOR = {
		[1] = {
			{
			id = "cursor_ravager",
			name = "Cursor Ravager",
			descNl = "Gooit Ravager of Bladestorm direct op je muispositie.",
			descEn = "Cast Ravager or Bladestorm at your cursor.",
			macro = [=[#showtooltip Ravager
/cast [@cursor] Ravager]=],
			},
			{
			id = "mouseover_intervene",
			name = "Mouseover Intervene",
			descNl = "Snoeft direct naar het teamlid onder je muis om schade op te vangen.",
			descEn = "Intervene to the teammate under your cursor to soak damage.",
			macro = [=[#showtooltip Intervene
/cast [@mouseover,help,nodead][] Intervene]=],
			},
		},
		[2] = {
			{
			id = "cursor_spear",
			name = "Cursor Spear",
			descNl = "Gooit je speer/ravager direct op je muispositie.",
			descEn = "Throw your spear or Ravager at your cursor.",
			macro = [=[#showtooltip Spear of Bastion
/cast [@cursor] Spear of Bastion]=],
			},
		},
		[3] = {
			{
			id = "mouseover_intervene",
			name = "Mouseover Intervene",
			descNl = "Vliegt naar een teamlid toe om ze te beschermen.",
			descEn = "Intervene to a teammate to protect them.",
			macro = [=[#showtooltip Intervene
/cast [@mouseover,help,nodead][] Intervene]=],
			},
			{
			id = "cursor_heroic_leap",
			name = "Cursor Heroic Leap",
			descNl = "Springt direct naar de locatie van je muis.",
			descEn = "Leap to your cursor.",
			macro = [=[#showtooltip Heroic Leap
/cast [@cursor] Heroic Leap]=],
			},
		},
	},
}

