#!/usr/bin/env python3
"""Build Modules/GuideTipSpellNames.lua from GuideData + GuideTips enUS strings."""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
guide_data = (ROOT / "Addons" / "GuideData.lua").read_text(encoding="utf-8")
tips_lua = (ROOT / "Locales" / "GuideTips.lua").read_text(encoding="utf-8")
en_block = re.search(r"merge\(ns\._mhLocales and ns\._mhLocales\.enUS, \{([^}]+)\}", tips_lua, re.S)
if not en_block:
    raise SystemExit("enUS block not found")
en_tips = dict(re.findall(r'\["(GUIDE_TIP_\d+)"\] = "((?:[^"\\]|\\.)*)"', en_block.group(1)))

rows = re.findall(
    r"\{\s*spell\s*=\s*(\d+)\s*,\s*textKey\s*=\s*\"(GUIDE_TIP_\d+)\"\s*\}",
    guide_data,
)
spell_en = {}
for sid, key in rows:
    text = en_tips.get(key, "").replace("\\n", "\n").replace('\\"', '"')
    if not text:
        continue
    m = re.match(r"^(.+?)\s+(?:is |are |quickly |must |should |use |gives |has |can |will |helps |keeps |lets |does |builds |applies |places |delivers |start |don't |do not )", text, re.I)
    if m:
        name = m.group(1).strip()
        if len(name) >= 3:
            spell_en[int(sid)] = name

lines = [
    "--[[ Auto-generated by tools/build_guide_tip_spell_en.py — English spell names for tip substitution. ]]",
    "",
    "local _, ns = ...",
    "",
    "ns.MH_GuideTipSpellEnName = {",
]
for sid in sorted(spell_en):
    name = spell_en[sid].replace("\\", "\\\\").replace('"', '\\"')
    lines.append(f"\t[{sid}] = \"{name}\",")
lines.append("}")
lines.append("")

out = ROOT / "Modules" / "GuideTipSpellNames.lua"
out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"Wrote {out} ({len(spell_en)} spells)")
