#!/usr/bin/env python3
"""Generate Modules/ConsumablesWowheadData.lua from data/consumables_wowhead.json."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

CLASS_TO_TOKEN = {
    "Death Knight": "DEATHKNIGHT",
    "Demon Hunter": "DEMONHUNTER",
    "Druid": "DRUID",
    "Evoker": "EVOKER",
    "Hunter": "HUNTER",
    "Mage": "MAGE",
    "Monk": "MONK",
    "Paladin": "PALADIN",
    "Priest": "PRIEST",
    "Rogue": "ROGUE",
    "Shaman": "SHAMAN",
    "Warlock": "WARLOCK",
    "Warrior": "WARRIOR",
}

SPEC_TO_INDEX = {
    "DEATHKNIGHT": {"Blood": 1, "Frost": 2, "Unholy": 3},
    "DEMONHUNTER": {"Havoc": 1, "Vengeance": 2},
    "DRUID": {"Balance": 1, "Feral": 2, "Guardian": 3, "Restoration": 4},
    "EVOKER": {"Devastation": 1, "Preservation": 2, "Augmentation": 3},
    "HUNTER": {"Beast Mastery": 1, "Marksmanship": 2, "Survival": 3},
    "MAGE": {"Arcane": 1, "Fire": 2, "Frost": 3},
    "MONK": {"Brewmaster": 1, "Mistweaver": 2, "Windwalker": 3},
    "PALADIN": {"Holy": 1, "Protection": 2, "Retribution": 3},
    "PRIEST": {"Discipline": 1, "Holy": 2, "Shadow": 3},
    "ROGUE": {"Assassination": 1, "Outlaw": 2, "Subtlety": 3},
    "SHAMAN": {"Elemental": 1, "Enhancement": 2, "Restoration": 3},
    "WARLOCK": {"Affliction": 1, "Demonology": 2, "Destruction": 3},
    "WARRIOR": {"Arms": 1, "Fury": 2, "Protection": 3},
}

CATEGORIES = (
    "flask",
    "combatPotion",
    "healingPotion",
    "weaponOil",
    "augmentRune",
    "feast",
    "personalFood",
)


def lua_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def emit_category_block(cat_obj: dict, indent: str) -> list[str]:
    best = [int(it["id"]) for it in (cat_obj.get("best") or []) if it.get("id")]
    alts = [int(it["id"]) for it in (cat_obj.get("alternates") or []) if it.get("id")]
    note_en = lua_escape(cat_obj.get("noteEn") or "")
    note_nl = lua_escape(cat_obj.get("noteNl") or "")
    lines = [f"{indent}best = {{ " + ", ".join(str(i) for i in best) + " },"]
    lines.append(f"{indent}alternates = {{ " + ", ".join(str(i) for i in alts) + " },")
    if note_en:
        lines.append(f'{indent}noteEn = "{note_en}",')
    if note_nl:
        lines.append(f'{indent}noteNl = "{note_nl}",')
    return lines


def main() -> int:
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "data" / "consumables_wowhead.json"
    out = ROOT / "Modules" / "ConsumablesWowheadData.lua"
    if not src.is_file():
        print(f"Missing: {src}", file=sys.stderr)
        return 1

    data = json.loads(src.read_text(encoding="utf-8"))
    meta = data.get("meta") or {}
    nested: dict[str, dict[int, dict]] = {}

    for class_name, specs in data.items():
        if class_name == "meta":
            continue
        token = CLASS_TO_TOKEN.get(class_name)
        if not token:
            print(f"Skip class: {class_name}", file=sys.stderr)
            continue
        spec_map = SPEC_TO_INDEX.get(token, {})
        nested.setdefault(token, {})
        for spec_name, spec_data in specs.items():
            idx = spec_map.get(spec_name)
            if not idx:
                print(f"Skip spec: {class_name} / {spec_name}", file=sys.stderr)
                continue
            entry: dict = {}
            if spec_data.get("omitWeaponOil"):
                entry["omitWeaponOil"] = True
            for cat in CATEGORIES:
                if cat == "weaponOil" and spec_data.get("omitWeaponOil"):
                    continue
                cat_obj = spec_data.get(cat)
                if cat_obj:
                    entry[cat] = cat_obj
            nested[token][idx] = entry

    lines = [
        "--[[",
        "\tWowhead-style consumables per class + spec (Midnight S1).",
        "\tGenerated by tools/generate_consumables_lua.py — edit JSON and re-run.",
        "\tItem names resolve in-game via item ID.",
        "]]",
        "",
        "local addonName, ns = ...",
        "",
        "ns.ConsumablesWowheadMeta = {",
        f'\tgameVersion = "{lua_escape(str(meta.get("gameVersion", "")))}",',
        f'\tcontentPhase = "{lua_escape(str(meta.get("contentPhase", "")))}",',
        f'\tgeneratedAt = "{lua_escape(str(meta.get("generatedAt", "")))}",',
        "}",
        "",
        "ns.ConsumablesWowheadByClassSpec = {}",
    ]

    for token in sorted(nested.keys()):
        lines.append(f"ns.ConsumablesWowheadByClassSpec.{token} = {{")
        for spec_idx in sorted(nested[token].keys()):
            lines.append(f"\t[{spec_idx}] = {{")
            spec_data = nested[token][spec_idx]
            if spec_data.get("omitWeaponOil"):
                lines.append("\t\tomitWeaponOil = true,")
            for cat in CATEGORIES:
                if cat not in spec_data:
                    continue
                lines.append(f"\t\t{cat} = {{")
                lines.extend(emit_category_block(spec_data[cat], "\t\t\t"))
                lines.append("\t\t},")
            lines.append("\t},")
        lines.append("}")
        lines.append("")

    out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"Wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
