#!/usr/bin/env python3
"""Turn the raw i18n audit into a work package a translator can actually use.

WHY THIS EXISTS (2026-07-29). The audit reported 1703 keys missing for
de/fr/es/pt, and 1288 of them were dead: GUIDE_ADVISOR (1128) and GUIDE_GEAR
(160) belong to the per-class levelling guide removed in 88907a2. The feature is
gone and nothing references those keys, but their enUS strings were left behind in
enUS.lua, so the audit still counts them as untranslated. Handing that list to a
volunteer would have asked them to translate a thousand strings for a screen that
no longer exists.

HOW A KEY IS JUDGED. Not by an exclusion list -- that would rot the moment another
feature is removed. For each key we ask whether ANY prefix of it appears in the
addon's own Lua outside Locales/. Prefixes, not the whole key, because plenty of
strings are built at runtime (ns:L("HEALCD_" .. kind)), so the full key never
appears literally anywhere.

Conservative on purpose: a key counts as LIVE unless no prefix of it, down to two
segments, turns up in the code. When in doubt it stays in the package. Being asked
to translate one dead string wastes a minute; dropping a live one silently ships a
raw key to a player.

Usage:  python tools/i18n_workpackage.py
Reads:  tools/i18n_worksheet_defrespt.txt, tools/i18n_worksheet_itIT.txt
Writes: tools/i18n_workpackage.md   (status + the live keys, paste-ready)
        tools/i18n_orphans.txt      (the dead ones, for a separate cleanup)
"""

import io
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOCALES = ROOT / "Locales"

WORKSHEETS = [
    ("de/fr/es/pt", ROOT / "tools" / "i18n_worksheet_defrespt.txt"),
    ("itIT", ROOT / "tools" / "i18n_worksheet_itIT.txt"),
]


def code_text():
    """Every .lua in the addon except the locale packs, as one blob."""
    parts = []
    for path in ROOT.rglob("*.lua"):
        if LOCALES in path.parents or path.parent.name == "tools":
            continue
        try:
            parts.append(path.read_text(encoding="utf-8", errors="replace"))
        except OSError:
            pass
    return "\n".join(parts)


def prefixes(key):
    """KEY_A_B_C -> ['KEY_A_B_C', 'KEY_A_B_', 'KEY_A_'] (longest first).

    The trailing underscore matters: it is what a runtime concatenation looks
    like in the source, and it stops KEY_A_ from matching an unrelated KEY_ABC.
    """
    parts = key.split("_")
    out = [key]
    for n in range(len(parts) - 1, 1, -1):
        out.append("_".join(parts[:n]) + "_")
    return out


def parse_worksheet(path):
    """-> list of (key, english). Skips the '## GROUP (n)' headers."""
    if not path.exists():
        return []
    rows = []
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if not line or line.startswith("#"):
            continue
        if "\t" not in line:
            continue
        key, eng = line.split("\t", 1)
        key = key.strip()
        if re.fullmatch(r"[A-Z][A-Z0-9_]+", key):
            rows.append((key, eng.strip()))
    return rows


def group_of(key):
    parts = key.split("_")
    return "_".join(parts[:2]) if len(parts) > 2 else key


def main():
    code = code_text()
    live_cache = {}

    def is_live(key):
        for p in prefixes(key):
            if p in live_cache:
                if live_cache[p]:
                    return True
                continue
            hit = p in code
            live_cache[p] = hit
            if hit:
                return True
        return False

    md = []
    md.append("# Midnight Helper — translation work package")
    md.append("")
    md.append(
        "Generated by `tools/i18n_workpackage.py`. Every line is `KEY <TAB> English`. "
        "Translate the right-hand side only; keep the KEY exactly as it is, and keep "
        "`%s`, `%d` and `|cff...|r` colour codes untouched."
    )
    md.append("")

    orphan_lines = []
    summary = []

    for label, path in WORKSHEETS:
        rows = parse_worksheet(path)
        if not rows:
            continue
        live = [(k, v) for k, v in rows if is_live(k)]
        dead = [(k, v) for k, v in rows if not is_live(k)]
        summary.append((label, len(rows), len(live), len(dead)))

        md.append("## %s — %d keys" % (label, len(live)))
        md.append("")
        groups = {}
        for k, v in live:
            groups.setdefault(group_of(k), []).append((k, v))
        for g in sorted(groups, key=lambda g: (-len(groups[g]), g)):
            md.append("### %s (%d)" % (g, len(groups[g])))
            md.append("```")
            for k, v in sorted(groups[g]):
                md.append("%s\t%s" % (k, v))
            md.append("```")
            md.append("")

        orphan_lines.append("=== %s: %d dead keys ===" % (label, len(dead)))
        dgroups = {}
        for k, _ in dead:
            dgroups.setdefault(group_of(k), []).append(k)
        for g in sorted(dgroups, key=lambda g: -len(dgroups[g])):
            orphan_lines.append("%-24s %d" % (g, len(dgroups[g])))
        orphan_lines.append("")

    head = ["", "| package | audit says missing | really to translate | dead (feature removed) |",
            "|---|---|---|---|"]
    for label, total, nlive, ndead in summary:
        head.append("| %s | %d | **%d** | %d |" % (label, total, nlive, ndead))
    head.append("")
    md[3:3] = head

    out = ROOT / "tools" / "i18n_workpackage.md"
    io.open(str(out) + ".tmp", "w", encoding="utf-8", newline="").write("\n".join(md) + "\n")
    os.replace(str(out) + ".tmp", str(out))

    orph = ROOT / "tools" / "i18n_orphans.txt"
    io.open(str(orph) + ".tmp", "w", encoding="utf-8", newline="").write("\n".join(orphan_lines) + "\n")
    os.replace(str(orph) + ".tmp", str(orph))

    for label, total, nlive, ndead in summary:
        print("%-12s audit %4d  ->  translate %4d,  dead %4d" % (label, total, nlive, ndead))
    print("\nwork package: %s" % out)
    print("orphans:      %s" % orph)


if __name__ == "__main__":
    main()
